Traceback (most recent call last):
  File "/home/aema/Desktop/DL2_erwin/./experiments/train_cosmology.py", line 185, in <module>
    fit(config, model, optimizer, scheduler, train_loader, valid_loader, test_loader, 100, 200)
  File "/home/aema/Desktop/DL2_erwin/training.py", line 127, in fit
    stat_dict = train_step(model, batch, optimizer, scheduler)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aema/Desktop/DL2_erwin/training.py", line 59, in train_step
    stat_dict = model.training_step(batch)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aema/Desktop/DL2_erwin/experiments/wrappers/cosmology_equi.py", line 44, in training_step
    return self.step(batch, "train")
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aema/Desktop/DL2_erwin/experiments/wrappers/cosmology_equi.py", line 39, in step
    pred_mv, pred_s = self(batch["pos"], **batch)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aema/Desktop/DL2_erwin/erwin/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aema/Desktop/DL2_erwin/erwin/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aema/Desktop/DL2_erwin/experiments/wrappers/cosmology_equi.py", line 35, in forward
    scalars = x_s2 + x_s,
             ~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'Tensor' and 'NoneType'
